host-name www.localhost.com
relay-domain www.localhost.com
<domain www.localhost.com>
         smtp-hosts [127.0.0.1]:25
         
</domain>



total-max-smtp-out 400 #amount of threads you want mailer to send at
total-max-smtp-in 1000 #amount of threads you want to allow for incoming mails

############################################################################
# BEGIN: ISP rules
############################################################################

domain-macro tld com, de, co.uk, es, net, ca, fr, com.tw, in, org, de, com.cn, com.tr, com.ph, com.br, com.au, com.vn, com.sg, co.in, co.id, co.nz, com.mx, ie, co.kr
domain-macro aolyahoo yahoo, ymail, y7mail, rocketmail, sbcglobal, att, bellsouth, aol, aim, wmconnect.com, netscape.net, compuserve, cs, marktoob, oddpost, kimo, geocities, schms, btinternet, rogers, rocketmail, verizon, flash, icloud
domain-macro hotmail hotmail, live, msn, outlook
domain-macro gmail gmail
domain-macro other cox, comcast, charter, rr

<domain *>
smtp-pattern-list backoff
smtp-pattern-list blocking-errors
smtp-greeting-timeout 5m
dkim-sign yes
dkim-algorithm rsa-sha1
dkim-body-canon relaxed
dkim-headers-canon relaxed
dkim-add-body-limit no
dkim-add-timestamp no
dkim-expire-after never
max-msg-rate 1500000/h
use-starttls yes
require-starttls no
track-recipient-events true
#1
bounce-after 1m
bounce-upon-no-mx yes
</domain>

# <domain $aolyahoo.$tld>
#  smtp-pattern-list backoff
#  smtp-pattern-list blocking-errors
 #backoff 1
#  backoff-to-normal-after 1h
#  queue-priority  75
#  smtp-421-means-mx-unavailable yes
#  replace-smtp-421-service-response yes
#  max-msg-rate 150/h ## ay ##
#  max-connect-rate 10/h ## ay ##
#  retry-after 20m,20m,20m,30m,30m,1h,2h,2h,4h,4h
  #backoff2ip
#  backoff-max-msg-rate 2/h
#  backoff-upon-all-sources-disabled yes
#  backoff-to-normal-after-delivery yes
#  bounce-upon-5xx-greeting false
# </domain>

#<domain $hotmail.$tld>
#  smtp-pattern-list backoff
#  smtp-pattern-list blocking-errors
#  max-msg-rate 150/h ## hotmail ##
#  max-errors-per-connection 10
#  max-connect-rate 80/h ## hotmail ##
#  backoff-to-normal-after 4h
#  bounce-upon-5xx-greeting yes
#  smtp-421-means-mx-unavailable yes
#</domain>

#<domain $gmail.$tld>
#  smtp-pattern-list backoff
#  smtp-pattern-list blocking-errors
#  max-msg-rate 150/h ## gmail ##
#  max-connect-rate 10/h ## gmail ##
#  backoff-to-normal-after 4h
#  smtp-421-means-mx-unavailable yes
#</domain>

#<domain $other.$tld>
# smtp-pattern-list backoff
#  smtp-pattern-list blocking-errors
#  max-msg-rate 200/h
#  max-connect-rate 10/h
#  backoff-to-normal-after 4h
#  queue-priority  75
#  bounce-upon-5xx-greeting yes
#  smtp-421-means-mx-unavailable yes
#  backoff-to-normal-after-delivery yes
#  connect-timeout 1m
#  smtp-greeting-timeout 5m
#  dkim-sign yes
#  dkim-algorithm rsa-sha1
#  dkim-body-canon relaxed
#  dkim-headers-canon relaxed
#  dkim-add-body-limit no
#  dkim-add-timestamp no
#  dkim-expire-after never
  #tls
#  use-starttls TRUE
#  require-starttls no
#</domain>


mx-connection-limit * 999999

#Domains to Block Based on MX
mx-connection-limit [*.]xmission.com 0
mx-connection-limit [*.]xmission.net 0
mx-connection-limit [*.]isux.com 0
mx-connection-limit [*.]isux.net 0
mx-connection-limit [*.]isux.org 0
mx-connection-limit [*.]sorbs.net 0
mx-connection-limit [*.]sorbs.com 0
mx-connection-limit [*.]usfamily.net 0
mx-connection-limit [*.]usfamily.com 0
mx-connection-limit [*.]spamexperts.com 0



######

############################################################################
# END: ISP rules
############################################################################

############################################################################
# BEGIN: BACKOFF RULES
############################################################################

<smtp-pattern-list backoff>
reply /generating high volumes of.* complaints from AOL/ mode=backoff
reply /Excessive unknown recipients - possible Open Relay/ mode=backoff
reply /^421 .* too many errors/ mode=backoff
reply /blocked.*spamhaus/ mode=backoff
reply /451 Rejected/ mode=backoff
</smtp-pattern-list>

<smtp-pattern-list blocking-errors>
reply /421 .* SERVICE NOT AVAILABLE/ mode=backoff
reply /generating high volumes of.* complaints from AOL/ mode=backoff
reply /554 .*aol.com/ mode=backoff
reply /421dynt1/ mode=backoff
reply /HVU:B1/ mode=backoff
reply /DNS:NR/ mode=backoff
reply /RLY:NW/ mode=backoff
reply /DYN:T1/ mode=backoff
reply /RLY:BD/ mode=backoff
reply /RLY:CH2/ mode=backoff
reply /421 .* Please try again later/ mode=backoff
reply /421 Message temporarily deferred/ mode=backoff
reply /VS3-IP5 Excessive unknown recipients/ mode=backoff
reply /VSS-IP Excessive unknown recipients/ mode=backoff
reply /\[GL01\] Message from/ mode=backoff
reply /\[TS01\] Messages from/ mode=backoff
reply /\[TS02\] Messages from/ mode=backoff
reply /\[TS03\] All messages from/ mode=backoff
reply /exceeded the rate limit/ mode=backoff
reply /exceeded the connection limit/ mode=backoff
reply /Mail rejected by Windows Live Hotmail for policy reasons/ mode=backoff
reply /mail.live.com\/mail\/troubleshooting.aspx/ mode=backoff
reply /421 Message Rejected/ mode=backoff
reply /Client host rejected/ mode=backoff
reply /blocked using UCEProtect/ mode=backoff
reply /Mail Refused/ mode=backoff
reply /421 Exceeded allowable connection time/ mode=backoff
reply /amIBlockedByRR/ mode=backoff
reply /block-lookup/ mode=backoff
reply /Too many concurrent connections from source IP/ mode=backoff
reply /too many/ mode=backoff
reply /Exceeded allowable connection time/ mode=backoff
reply /Connection rate limit exceeded/ mode=backoff
reply /refused your connection/ mode=backoff
reply /try again later/ mode=backoff
reply /try later/ mode=backoff
reply /550 RBL/ mode=backoff
reply /TDC internal RBL/ mode=backoff
reply /connection refused/ mode=backoff
reply /please see www.spamhaus.org/ mode=backoff
reply /Message Rejected/ mode=backoff
reply /refused by antispam/ mode=backoff
reply /Service not available/ mode=backoff
reply /currently blocked/ mode=backoff
reply /locally blacklisted/ mode=backoff
reply /not currently accepting mail from your ip/ mode=backoff
reply /421.*closing connection/ mode=backoff
reply /421.*Lost connection/ mode=backoff
reply /476 connections from your host are denied/ mode=backoff
reply /421 Connection cannot be established/ mode=backoff
reply /421 temporary envelope failure/ mode=backoff
reply /421 4.4.2 Timeout while waiting for command/ mode=backoff
reply /450 Requested action aborted/ mode=backoff
reply /550 Access denied/ mode=backoff
reply /exceeded the rate limit/ mode=backoff
reply /421rlynw/ mode=backoff
reply /permanently deferred/ mode=backoff
reply /\d+\.\d+\.\d+\.\d+ blocked/ mode=backoff
reply /www\.spamcop\.net\/bl\.shtml/ mode=backoff
reply /generating high volumes of.* complaints from AOL/ mode=backoff
reply /Excessive unknown recipients - possible Open Relay/ mode=backoff
reply /^421 .* too many errors/ mode=backoff
reply /blocked.*spamhaus/ mode=backoff
reply /451 Rejected/ mode=backoff
</smtp-pattern-list>

############################################################################
# END: BACKOFF RULES
############################################################################

############################################################################
# BEGIN: BOUNCE RULES
############################################################################

<bounce-category-patterns>
/spam/ spam-related
/junk mail/ spam-related
/blacklist/ spam-related
/blocked/ spam-related
/\bU\.?C\.?E\.?\b/ spam-related
/\bAdv(ertisements?)?\b/ spam-related
/unsolicited/ spam-related
/\b(open)?RBL\b/ spam-related
/realtime blackhole/ spam-related
/http:\/\/basic.wirehub.nl\/blackholes.html/ spam-related
/\bvirus\b/ virus-related
/message +content/ content-related
/content +rejected/ content-related
/quota/ quota-issues
/limit exceeded/ quota-issues
/mailbox +(is +)?full/ quota-issues
/\bstorage\b/ quota-issues
/(user|mailbox|recipient|rcpt|local part|address|account|mail drop|ad(d?)ressee) (has|has been|is)? *(currently|temporarily 
+)?(disabled|expired|inactive|not

activated)/ inactive-mailbox
/(conta|usu.rio) inativ(a|o)/ inactive-mailbox
/Too many (bad|invalid|unknown|illegal|unavailable) (user|mailbox|recipient|rcpt|local part|address|account|mail drop|ad(d?)ressee)/ other
/(No such|bad|invalid|unknown|illegal|unavailable) (local +)?(user|mailbox|recipient|rcpt|local part|address|account|mail drop|ad(d?)ressee)/ bad-mailbox
/(user|mailbox|recipient|rcpt|local part|address|account|mail drop|ad(d?)ressee) +(\S+@\S+ +)?(not (a +)?valid|not known|not here|not found|does not 
exist|bad|

invalid|unknown|illegal|unavailable)/ bad-mailbox
/\S+@\S+ +(is +)?(not (a +)?valid|not known|not here|not found|does not exist|bad|invalid|unknown|illegal|unavailable)/ bad-mailbox
/no mailbox here by that name/ bad-mailbox
/my badrcptto list/ bad-mailbox
/not our customer/ bad-mailbox
/no longer (valid|available)/ bad-mailbox
/have a \S+ account/ bad-mailbox
/\brelay(ing)?/ relaying-issues
/domain (retired|bad|invalid|unknown|illegal|unavailable)/ bad-domain
/domain no longer in use/ bad-domain
/domain (\S+ +)?(is +)?obsolete/ bad-domain
/denied/ policy-related
/prohibit/ policy-related
/rejected/ policy-related
/refused/ policy-related
/allowed/ policy-related
/banned/ policy-related
/policy/ policy-related
/suspicious activity/ policy-related
/bad sequence/ protocol-errors
/syntax error/ protocol-errors
/\broute\b/ routing-errors
/\bunroutable\b/ routing-errors
/\bunrouteable\b/ routing-errors
/^2.\d.\d/ success
/^[45]\.1\.1/ bad-mailbox
/^[45]\.1\.2/ bad-domain
/^[45]\.3\.5/ bad-configuration
/^[45]\.4\.1/ no-answer-from-host
/^[45]\.4\.2/ bad-connection
/^[45]\.4\.4/ routing-errors
/^[45]\.4\.6/ routing-errors
/^[45]\.4\.7/ message-expired
/^[45]\.7\.1/ policy-related
// other    # catch-all
/failed\,5\.0\.0 \(undefined status\)\,x\-pmta\;bounce\-queue/ bad-domain
</bounce-category-patterns>

############################################################################
# END: BOUNCE RULES
############################################################################

############################################################################
# BEGIN: OTHER OPTIONS
############################################################################

#postmaster abuse@ywhbjgz.cn
smtp-listener 0/0:2525 

<source 0/0> 
allow-unencrypted-plain-auth yes
always-allow-relaying yes
allow-starttls yes
jobid-header x-job
process-x-job yes
hide-message-source true 

suppress-local-dsn no
</source> 


sync-msg-create false 
sync-msg-update false 
run-as-root no 
log-file /var/log/pmta/log # logrotate is used for rotation 

<acct-file /var/log/pmta/acct.csv>
#    move-to /opt/myapp/pmta-acct   # configure as fit for your application
move-interval 5m
max-size 200M
</acct-file>

# transient errors (soft bounces)
<acct-file /var/log/pmta/diag.csv>
move-interval 5m
delete-after never
records t
</acct-file>

<domain {gmImprinter}>
max-events-recorded 150
log-messages yes
log-data no # extremely verbose, for debugging only
retry-after 15s
</domain>

#
# spool directories
#
<spool /var/spool/pmta> 
delete-file-holders yes
</spool> 

http-mgmt-port 49253
http-access 178.157.56.204 admin

http-redirect-to-https false


#######################################
# END: OTHER OPTIONS
############################################################################


############################################################################
# BEGIN: USERS/VIRTUAL-MTA / VIRTUAL-MTA-POOL / VIRTUAL-PMTA-PATTERN
############################################################################

<smtp-user namr@yuming> 
password Mima123456..
source {pmta-auth} 
</smtp-user>

<source {pmta-auth}>
       smtp-service yes
    always-allow-relaying yes
    require-auth true
    process-x-virtual-mta yes
    default-virtual-mta pmta-pool-001
    remove-received-headers true
    add-received-header false
    hide-message-source true
    remove-header X-PreviewEmail,X-Mailer,X-Mailer-RecptId,X-Mailer-Sent-By,X-Priority
	allow-starttls yes
</source>

 


